#!/bin/sh

if test "$1" = "init"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include"

    autoreconf --force
    aclocal
    autoheader
    autoreconf
    automake --add-missing
    libtoolize
    make distclean
    autoreconf
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib -L/usr/local/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include -I/usr/local/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev-memdebug"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include -DDO_MEMDEBUG"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev-rdtsc"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug --with-rdtsc

elif test "$1" = "dev-ev"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib -L/usr/local/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include -I/usr/local/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug --with-ev

elif test "$1" = "dev-ev-memdebug"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib -L/usr/local/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include -I/usr/local/include -DDO_MEMDEBUG"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug --with-ev

elif test "$1" = "dev-ndebug"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME

elif test "$1" = "dev-ndebug-rdtsc"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME --with-rdtsc

elif test "$1" = "dev-ndebug-static"
then
    export LDFLAGS="${LDFLAGS} -L$HOME/lib -L/usr/local/lib"
    export CFLAGS="${CFLAGS} -I$HOME/include -I/usr/local/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-allstatic --enable-lto

elif test "$1" = "dist"
then
    unset LDFLAGS
    unset CFLAGS
    autoreconf
    ./configure
    make dist

    if test -f port/distinfo
    then
        truncate -s0 port/distinfo
    fi
    for i in *.tar.gz
    do
        cp -v $i /data0/mkushnir/distfiles/
        if test -f port/distinfo
        then
            /sbin/sha256 $i >port/distinfo
            echo "SIZE ($i) = `stat -f%z $i`" >>port/distinfo
        fi
    done

elif test "$1" = "du"
then
    find . -type f -name '*.[ch]' -ls | awk '{print $7;}' | (n=0; while read a; do n=$((n + a)); done; echo $n)

else
    echo "`basename $0` {init|dev|dist|dev-ndebug|dev-rdtsc|dev-ndebug-static}"
fi
